### ISSUE TITLE
I want to contribute to this ⭐ 

### ISSUE THREAD

**Issue by dammy95** [dynamic2code/Donation_tracking#1]
Hello @dynamic2code 👋🏾 

I'm a Software Developer from Nigeria and would like to contribute to this project. I can do 2-3 hours a day, but will need an initial starting point for contribution (bug fixes, features, tests, etc).

I saw your post on LinkedIn and was intrigued by it. Happy to start collaboration immediately.

**Comment by dynamic2code** [comment]
Hello,
Some of the documentation is at https://donation-tracking-nuxt.vercel.app/  . Currently am at the messaging part with Africa's talking on the back-end part. You could work on that.  Am working on the Nuxt app
